export const UPDATE_TIME = 'UPDATE_TIME';
export const UPDATE_FORMAT = 'UPDATE_FORMAT';
export const RESET_TIME = 'RESET_TIME';
export const RESTORE_ALL_DEFAULTS = 'RESTORE_ALL_DEFAULTS';

export const ADD_BUTTON = 'ADD_BUTTON';
export const REMOVE_BUTTONS = 'REMOVE_BUTTONS';
